server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver

    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml


  data:
    redis:
      host: 127.0.0.1
      port: 6379

  mvc:
    view:
      prefix: /templates/
      suffix: .html


#别他妈的动我的amap-key，就这么放着，草泥马！！！！！
short-link:
  domain:
    default: baidudd.com:8001
  goto-domain:
    white-list:
      enable: true
      names: 哔哩哔哩、百度、GitHub
      details:
        - bilibili.com
        - baidu.com
        - github.com
  stats:
    locale:
      amap-key: c831801a8d8129b67c64f6a05a369b4c
